// Creación de equipos con grupos para un torneo
team Brasil {
    badge { // Creación de figurita del escudo de Brasil
        Photo: https://upload.wikimedia.org/wikipedia/commons/1/1b/Logo_Brasil.png;
    },
    player Neymar { // Creación de figurita de Neymar
        Birthdate: 5/2/1992;
        Height: 1.75;
        Weight: 68;
        Team: Santos FC;
        Photo: https://b.fssta.com/uploads/application/soccer/headshots/713.png;
    },
    player Thiago Silva { // Creación de figurita de Thiago Silva
        Birthdate: 22/9/1984;
        Height: 1.83;
        Weight: 79;
        Team: AC Milan;
        Photo: https://m.media-amazon.com/images/M/MV5BNWRmZjU3OGUtMjNjMC00YmY5LTk2NTgtN2QxMDY3MzIyNGNiXkEyXkFqcGdeQXVyMjUyNDk2ODc@._V1_.jpg;
    }
},
tournament Copa America {
    trophy Copa {
        Photo: https://www.directvsports.com/__export/1718715080604/sites/dsports/img/2024/06/18/sgf2csjbcvfxvfwnn7liq53u3y.jpg_135585964.jpg;
    },
    stadium MercedesBenz Stadium {
        Capacity: 71000;
        Photo: https://upload.wikimedia.org/wikipedia/commons/1/10/Mercedes_Benz_Stadium_time_lapse_capture_2017-08-13.jpg;
    },
    ball Jabulani {
        Photo: https://s.rfi.fr/media/display/797a3f40-12b1-11ea-ad06-005056a99247/w:1280/p:1x1/ballon-adidas-jabulani-2.jpg;
    },
    group A {
        team Argentina {
            badge { // Creación de figurita del escudo de Argentina
                Photo: https://seeklogo.com/images/A/afa-argentina-3-star-logo-CE85FC39D9-seeklogo.com.png;
            },
            player Angel Di Maria { // Creación de figurita de Di Maria
                Birthdate: 14/2/1988;
                Height: 1.78;
                Weight: 75;
                Team: Sport Lisboa e Benfica;
                Photo: https://upload.wikimedia.org/wikipedia/commons/8/8c/NIG-ARG_%285%29.jpg;
            },
            player Nicolas Otamendi { // Creación de figurita de Otamendi
                Birthdate: 12/2/1988;
                Height: 1.83;
                Weight: 82;
                Team: Sport Lisboa e Benfica;
                Photo: https://img.a.transfermarkt.technology/portrait/big/54781-1669835534.jpg;
            },
            player Lionel Messi { // Creación de figurita de Messi
                Birthdate: 24/6/1987;
                Height: 1.69;
                Weight: 67;
                Team: Inter Miami CF;
                Photo: https://fcb-abj-pre.s3.amazonaws.com/img/jugadors/MESSI.jpg;
            }
        },
        team Mexico {
            badge { // Creación de figurita del escudo de Mexico
                Photo: https://i.pinimg.com/736x/0e/c6/1b/0ec61bcddde0674ecf60b80112daf56d.jpg;
            },
            player Javier Hernandez { // Creación de figurita de Chicharito
                Birthdate: 1/6/1988;
                Height: 1.75;
                Weight: 73;
                Team: Manchester United;
                Photo: https://c3.klipartz.com/pngpicture/297/323/sticker-png-seleccion-mexicana-javier-hernandez-thumbnail.png;
            },
            player Andres Guardado { // Creación de figurita de Guardado
                Birthdate: 28/9/1986;
                Height: 1.69;
                Weight: 64;
                Team: Valencia CF;
                Photo: https://s.hs-data.com/bilder/spieler/gross/47979.jpg;
            }
        },
        team Uruguay {
            badge { // Creación de figurita del escudo de Uruguay
                Photo: https://seeklogo.com/images/A/asociacion-uruguaya-de-futbol-logo-8AE2DF5DB7-seeklogo.com.png;
            },
            player Diego Forlan { // Creación de figurita de Forlan
                Birthdate: 19/5/1979;
                Height: 1.80;
                Weight: 75;
                Team: Cerezo Osaka;
                Photo: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/U10_Diego_Forl%C3%A1n_7524.jpg/640px-U10_Diego_Forl%C3%A1n_7524.jpg;
            },
            player Luis Suarez { // Creación de figurita de Suarez
                Birthdate: 24/1/1987;
                Height: 1.82;
                Weight: 86;
                Team: Liverpool FC;
                Photo: https://auf.org.uy/imagenes/img_contenido/seleccion_jugador/a/sua-769-rez.jpg;
            }
        } 
    },
    group B {
        team Colombia {
            badge { // Creación de figurita del escudo de Colombia
                Photo: https://upload.wikimedia.org/wikipedia/commons/f/f0/Escudo_de_la_Federaci%C3%B3n_Colombiana_de_F%C3%BAtbol.png;
            },
            player James Rodriguez { // Creación de figurita de James Rodriguez
                Birthdate: 12/7/1991;
                Height: 1.80;
                Weight: 75;
                Team: AS Monaco;
                Photo: https://img.a.transfermarkt.technology/portrait/big/88103-1540568385.jpg;
            },
            player Radamel Falcao { // Creación de figurita de Falcao
                Birthdate: 10/2/1986;
                Height: 1.77;
                Weight: 72;
                Team: AS Monaco;
                Photo: https://www.eluniverso.com/resizer/sy2LvzVKHumKT4FQZ4jSRG7yOGg=/567x647/smart/filters:quality(70)/cloudfront-us-east-1.images.arcpublishing.com/eluniverso/NRKU5V2CGFB7RFLNQA5NKIG5E4.jpg;
            }
        },
        team Brasil // Already defined elsewhere
    }
}
